services:
    # Servicio para Composer
    composer:
        image: composer:latest
        container_name: laravel-composer
        working_dir: /var/www
        volumes:
            - ../mother:/var/www
        networks:
            - laravel
        command: install  # Ejecuta composer install cuando se inicie el contenedor

    # Servicio para Node.js (npm)
    node:
        image: node:latest
        container_name: laravel-node
        working_dir: /var/www
        volumes:
            - ../mother:/var/www
        networks:
            - laravel
        command: npm install  # Ejecuta npm install cuando se inicie el contenedor

    # Servicio para Laravel (PHP)
    app:
        image: php:8.2-fpm
        container_name: laravel-app
        working_dir: /var/www/html
        volumes:
            - ../mother:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel

    # Servidor Nginx
    webserver:
        image: nginx:latest
        container_name: laravel-web
        depends_on:
            - app
        volumes:
            - ../mother:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - laravel

    # Base de datos MariaDB
    db:
        image: mariadb:latest
        container_name: laravel-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Mg829697+*
            MYSQL_DATABASE: mother
            MYSQL_USER: gguser
            MYSQL_PASSWORD: Gg829697+
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel

volumes:
    db_data: # Volumen para almacenar los datos de MariaDB

networks:
    laravel:
