
services:
    # 🚀 Tu aplicación POS (Nginx + Laravel + Inertia + Vue + TS)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: mi-pos-app:latest
        container_name: pos_app
        restart: unless-stopped
        ports:
            - "8000:80" # El puerto por el que accederás en el navegador
        volumes:
            - ./.env:/var/www/html/.env
            - pos_storage:/var/www/html/storage
        networks:
            - pos_network # 🟢 Conectamos este contenedor a la red de tu base de datos
    web-sever:
        image: nginx:alpine
        container_name: pos_web-sever
        restart: unless-stopped
        depends_on:
            -   app
        ports:
            - "8090:80"


# 💾 Volúmenes persistentes para los archivos de Laravel
volumes:
    pos_storage:

# 🌐 Definimos la red compartida
networks:
    pos_network:
        external: true # 🟢 Le dice a Docker que use la red existente donde ya está tu base de datos
