/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const computed: typeof import('vue').computed
  const configPercent: typeof import('./Global/Helpers').configPercent
  const createApp: typeof import('vue').createApp
  const createSequence: typeof import('./Global/Helpers').createSequence
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const exportExcel: typeof import('./Global/Helpers').exportExcel
  const fielName: typeof import('./Global/Helpers').fielName
  const formatNumber: typeof import('./Global/Helpers').formatNumber
  const generateColors: typeof import('./Global/Helpers').generateColors
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getMoney: typeof import('./Global/Helpers').getMoney
  const getSearchTable: typeof import('./Global/SearchTable').getSearchTable
  const getSequenceType: typeof import('./Global/Helpers').getSequenceType
  const getYear: typeof import('./Global/Helpers').getYear
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const m: typeof import('./Global/Helpers').m
  const markRaw: typeof import('vue').markRaw
  const moneyConfig: typeof import('./Global/Helpers').moneyConfig
  const month: typeof import('./Global/Helpers').month
  const ms: typeof import('./Global/Helpers').ms
  const next: typeof import('./Global/Helpers').next
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const paginationJoin: typeof import('./Global/Helpers').paginationJoin
  const printPdf: typeof import('./Global/Helpers').printPdf
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const route: typeof import('ziggy-js').route
  const router: typeof import('@inertiajs/vue3').router
  const s: typeof import('./Global/Helpers').s
  const setHour: typeof import('./Global/Helpers').setHour
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const typePaymentData: typeof import('./Global/ShareData').typePaymentData
  const unref: typeof import('vue').unref
  const urlRNC: typeof import('./Global/Helpers').urlRNC
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useForm: typeof import('@inertiajs/vue3').useForm
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const usePage: typeof import('@inertiajs/vue3').usePage
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
}
